### ISSUE TITLE
Cannot move BB-8 or do anything outside of test program

### ISSUE THREAD

**Issue by JohnMackYouTube05** [jchadwhite/SpheroBB8-python#8]
Everytime I try to run anything in my own program with everything I need put in, I get this error.
`Traceback (most recent call last):
  File "BB8_move.py", line 11, in <module>
    bb8.roll(255, 0, "01h", False)
  File "/home/pi/SpheroBB8-python/BB8_driver.py", line 712, in roll
    response)
  File "/home/pi/SpheroBB8-python/BB8_driver.py", line 768, in send
    checksum = ~ sum(data) % 256
TypeError: unsupported operand type(s) for +: 'int' and 'str'
`

**Comment by JohnMackYouTube05** [comment]
Ok never mind, false alarm. I was using 01h as the status parameter instead of just 1. And that was throwing the whole program off.
